### ISSUE TITLE
Time domain audio loss from TFGAN paper

### ISSUE THREAD

**Issue by rishikksh20** [csteinmetz1/auraloss#10]
Hi @csteinmetz1 ,  recently in TFGAN paper https://arxiv.org/pdf/2011.12206.pdf author uses many time domain audio loss like Energy loss, Time loss and Phase loss. Do you have any roadmap to include these losses into this repo.

**Comment by csteinmetz1** [comment]
Hi @rishikksh20, thanks for bringing these losses to my attention! They are interesting and would be a great addition. I don't currently have a plan to implement them, but I will add them to my list. More than happy to accept a pull request if you are interested in starting an implementation.
