### ISSUE TITLE
Librosa warning when using MelSTFTLoss

### ISSUE THREAD

**Issue by csteinmetz1** [csteinmetz1/auraloss#33]
We get the following warning due to changes in the librosa interface. Should be easy to address.

```env/lib/python3.7/site-packages/auraloss/freq.py:138: FutureWarning: Pass sr=44100, n_fft=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error```

**Comment by sivannavis** [comment]
Hi @csteinmetz1 , could you please tell me if you solved this? I tried to add something like `librosa.filters.mel(sr=self.sample_rate, n_fft=self.n_fft, n_mels=self.n_mels))`, but the warning still shows up. Thank you!

**Comment by csteinmetz1** [comment]
This warning should not be fixed in #44 and there is a new release v0.3.0
